### ISSUE TITLE
有yolov5s的模型转换例子吗

### ISSUE THREAD

**Issue by long-fu** [AXERA-TECH/pulsar2-docs#3]

**Comment by long-fu** [comment]
yamain.common.error.CodeException: (<ErrorCode.NPUBackendError: 8>, KeyError('/model.24/Concat_1_output_0_ddr'))
这个错误是什么原因导致的

**Comment by BUG1989** [comment]
https://zhuanlan.zhihu.com/p/569083585 可以参考这篇知乎文章导出 YOLOv5s 的 ONNX 模型，然后在按照 quick star 章节中的配置文件进行转换。

**Comment by long-fu** [comment]
感谢解决了
